#idea from  https://github.com/sergeyz/symfony-demo/blob/master/environment/docker-compose.yml
version: '2.2'

services:
  # creating a container for data to reuse data instead of remounting volumes.
  data:
    image: alpine:3.4
    command: 'sleep 1s'
    working_dir: '/var/www/html'
    volumes:
      - "${SF_WORKSPACE:-/Users/a1/Documents/apps/footypicksphp}:/var/www/html"

  server:
    image: nginx:footy
    build: docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - data
    links:
      - php

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: footy
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 30s
      timeout: 5s
      retries: 20
    privileged: true
    ports:
      - "3306:3306"
#
#  key-value-storage:
#    image: redis:alpine
#    ports:
#      - "6379"

  composer:
    image: composer:1.4
    command: 'install --prefer-dist --no-suggest --optimize-autoloader --no-interaction --ignore-platform-reqs'
    working_dir: '/var/www/html'
    command: install
    volumes_from:
      - data
    healthcheck:
      test: ["CMD-SHELL", "test -f vendor/autoload.php"]
      interval: 30s
      timeout: 5s
      retries: 20

  # Note: as for now, it uses default php config. @todo copy prod config for fpm.
  php:
    image: php7:brandoo
    build: docker/php/7.0
    working_dir: '/var/www/html'
    depends_on:
      composer: { condition: service_healthy }
      database: { condition: service_healthy }
    links:
      - database
    volumes_from:
      - data
    ports:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "test -f app/config/parameters.yml"]
      interval: 30s
      timeout: 5s
      retries: 20